### PR TITLE
consolidated the header and outer-dom into a single "ubiquitous" name…

### LINKED ISSUE #65: move the header to its own namespace

### PR DESCRIPTION
**Pull request by thedavidmeister**
fixes #65

### CODE REVIEW

**Comment by thedavidmeister** [comment]
To get the warnings to go away, I had to move all the `.hl` files that just had elements out into `.cljs` files in the other folder.

**Comment by thedavidmeister** [comment]
I also had to "flatten" some of the namespaces, so instead of:

`foo/bar/baz.cljs` in a file with `(ns foo.bar) (defelem bing)`  inside it, we now have to do:

`foo/bar/baz.cljs` in a file with `(ns foo.bar.baz) (defelem bing)`.

I actually think this might fix *all* the compile warnings.

**Comment by thedavidmeister** [comment]
screen shot 2015-11-11 at 9 48 04 pm
screen shot 2015-11-11 at 9 47 59 pm

**Comment by thedavidmeister** [comment]
fixes #43

**Comment by meelijane** [comment]
:shipit:

**Pull request merged**
